### ISSUE TITLE
ComfyUI support!

### ISSUE THREAD

**Issue by toyxyz** [KohakuBlueleaf/z-tipo-extension#1]
Thank you for your wonderful work!

I have made some modifications to support comfyui.

Please check and tell me if you like it!

https://github.com/toyxyz/a1111-sd-webui-dtg_comfyui

![image](https://github.com/KohakuBlueleaf/a1111-sd-webui-dtg/assets/8006000/a1d16069-9818-49e3-81ab-640457179c98)

**Comment by yoinked-h** [comment]
made another version that uses gradio_client ( #2 )

**Comment by KohakuBlueleaf** [comment]
@toyxyz I think this is good but I have some small questions (may related to how comfyui load the custom nodes so if it some of the question/problem is unsovlable, ignore them)

1. Is the __init__.py in root path avoidable? Like add "os.path.basedir(__file__)" to sys.path temporarily.
2. The parse_attention code is from a1111, which is under AGPL3. I'm considering if ComfyUI have similar code for parsing emphasis for prompts and can allow you to import. (So you can avoid some license issue)

**Comment by toyxyz** [comment]
> @toyxyz I think this is good but I have some small questions (may related to how comfyui load the custom nodes so if it some of the question/problem is unsovlable, ignore them)
> 
> 1. Is the **init**.py in root path avoidable? Like add "os.path.basedir(**file**)" to sys.path temporarily.
> 2. The parse_attention code is from a1111, which is under AGPL3. I'm considering if ComfyUI have similar code for parsing emphasis for prompts and can allow you to import. (So you can avoid some license issue)

Thank you! but my programming skills are not very good, so I don't think I can give you a definitive answer. 

To the best of my knowledge, the answer is this.  
 
1. custom nodes won't work without __init__.py. 
Here's another extension that supports both webui and ComfyUI. 
https://github.com/mcmonkeyprojects/sd-dynamic-thresholding

3. ComfyUI has an parsing emphasis code. I don't know how to use it though. As I understand it, the emphasis of webui and comfyui is calculated a bit differently. 
There is a custom node for generating the same image as webui in comfyui. 
https://github.com/shiimizu/ComfyUI_smZNodes

**Comment by KohakuBlueleaf** [comment]
@toyxyz I have updated lot of logic inside my code and now I seperate the kgen into standalone projects

You may want to check it!
https://github.com/KohakuBlueleaf/KGen

**Comment by XJF2332** [comment]
> Thank you for your wonderful work!
> 
> I have made some modifications to support comfyui.
> 
> Please check and tell me if you like it!
> 
> https://github.com/toyxyz/a1111-sd-webui-dtg_comfyui
> 
> ![image](https://private-user-images.githubusercontent.com/8006000/316255850-a1d16069-9818-49e3-81ab-640457179c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTk5NDAsIm5iZiI6MTcyMzUxOTY0MCwicGF0aCI6Ii84MDA2MDAwLzMxNjI1NTg1MC1hMWQxNjA2OS05ODE4LTQ5ZTMtODFhYi02NDA0NTcxNzljOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDMyNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU0OTg2MDZkNmVmMzdjMzE5YjgyMjI2YzAzYTU1N2ZiYzFhMTAwNDIzZGQ4MjAwMjc3M2QyZWIyZGZmZGVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uOC-uiDy2Lbzgxy5yzKNpPAlISew6eDEcq4jggZRmDo)

I encountered an issue while installing your plugin.
Your `install.py` requires `launch`, after attempting to install `launch`, `pip` says `launch` requires `flowdas-meta`.
I tried `pip install flowdas-meta`, but `pip` errored out, saying it couldn't find a suitable version.
I found that `flowdas-meta` has been removed from `PyPI`, and I couldn't find a `tar.gz` file for manual installation.
Can you replace `launch` with other modules or provide a `tag.gz` file for `flowdas-meta`? 
Or, is there any other solution to this problem?
Thank you.

**Comment by KohakuBlueleaf** [comment]
> > Thank you for your wonderful work!
> > I have made some modifications to support comfyui.
> > Please check and tell me if you like it!
> > https://github.com/toyxyz/a1111-sd-webui-dtg_comfyui
> > ![image](https://private-user-images.githubusercontent.com/8006000/316255850-a1d16069-9818-49e3-81ab-640457179c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTk5NDAsIm5iZiI6MTcyMzUxOTY0MCwicGF0aCI6Ii84MDA2MDAwLzMxNjI1NTg1MC1hMWQxNjA2OS05ODE4LTQ5ZTMtODFhYi02NDA0NTcxNzljOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDMyNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU0OTg2MDZkNmVmMzdjMzE5YjgyMjI2YzAzYTU1N2ZiYzFhMTAwNDIzZGQ4MjAwMjc3M2QyZWIyZGZmZGVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uOC-uiDy2Lbzgxy5yzKNpPAlISew6eDEcq4jggZRmDo)
> 
> I encountered an issue while installing your plugin. Your `install.py` requires `launch`, after attempting to install `launch`, `pip` says `launch` requires `flowdas-meta`. I tried `pip install flowdas-meta`, but `pip` errored out, saying it couldn't find a suitable version. I found that `flowdas-meta` has been removed from `PyPI`, and I couldn't find a `tar.gz` file for manual installation. Can you replace `launch` with other modules or provide a `tag.gz` file for `flowdas-meta`? Or, is there any other solution to this problem? Thank you.

launch.py is for sd-webui to install essential dependencies.
if you are using comfy, you should ignore that file.

**Comment by XJF2332** [comment]
> > > Thank you for your wonderful work!
> > > I have made some modifications to support comfyui.
> > > Please check and tell me if you like it!
> > > https://github.com/toyxyz/a1111-sd-webui-dtg_comfyui
> > > ![image](https://private-user-images.githubusercontent.com/8006000/316255850-a1d16069-9818-49e3-81ab-640457179c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTk5NDAsIm5iZiI6MTcyMzUxOTY0MCwicGF0aCI6Ii84MDA2MDAwLzMxNjI1NTg1MC1hMWQxNjA2OS05ODE4LTQ5ZTMtODFhYi02NDA0NTcxNzljOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDMyNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU0OTg2MDZkNmVmMzdjMzE5YjgyMjI2YzAzYTU1N2ZiYzFhMTAwNDIzZGQ4MjAwMjc3M2QyZWIyZGZmZGVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uOC-uiDy2Lbzgxy5yzKNpPAlISew6eDEcq4jggZRmDo)
> > 
> > 
> > I encountered an issue while installing your plugin. Your `install.py` requires `launch`, after attempting to install `launch`, `pip` says `launch` requires `flowdas-meta`. I tried `pip install flowdas-meta`, but `pip` errored out, saying it couldn't find a suitable version. I found that `flowdas-meta` has been removed from `PyPI`, and I couldn't find a `tar.gz` file for manual installation. Can you replace `launch` with other modules or provide a `tag.gz` file for `flowdas-meta`? Or, is there any other solution to this problem? Thank you.
> 
> launch.py is for sd-webui to install essential dependencies. if you are using comfy, you should ignore that file.

thank you for solving that!
however, I ran into another warning saying that `Llama-cpp-python not found, using transformers to load model`, but I can find `llama-cpp-python` using `pip list`.
do you know the reason why?
![image](https://github.com/user-attachments/assets/14520ab0-14b7-4030-9771-0c1c828c6f83)

**Comment by XJF2332** [comment]
> > > Thank you for your wonderful work!
> > > I have made some modifications to support comfyui.
> > > Please check and tell me if you like it!
> > > https://github.com/toyxyz/a1111-sd-webui-dtg_comfyui
> > > ![image](https://private-user-images.githubusercontent.com/8006000/316255850-a1d16069-9818-49e3-81ab-640457179c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTk5NDAsIm5iZiI6MTcyMzUxOTY0MCwicGF0aCI6Ii84MDA2MDAwLzMxNjI1NTg1MC1hMWQxNjA2OS05ODE4LTQ5ZTMtODFhYi02NDA0NTcxNzljOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDMyNzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTU0OTg2MDZkNmVmMzdjMzE5YjgyMjI2YzAzYTU1N2ZiYzFhMTAwNDIzZGQ4MjAwMjc3M2QyZWIyZGZmZGVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uOC-uiDy2Lbzgxy5yzKNpPAlISew6eDEcq4jggZRmDo)
> > 
> > 
> > I encountered an issue while installing your plugin. Your `install.py` requires `launch`, after attempting to install `launch`, `pip` says `launch` requires `flowdas-meta`. I tried `pip install flowdas-meta`, but `pip` errored out, saying it couldn't find a suitable version. I found that `flowdas-meta` has been removed from `PyPI`, and I couldn't find a `tar.gz` file for manual installation. Can you replace `launch` with other modules or provide a `tag.gz` file for `flowdas-meta`? Or, is there any other solution to this problem? Thank you.
> 
> launch.py is for sd-webui to install essential dependencies. if you are using comfy, you should ignore that file.

btw, although the tab says `C:\Windows\system32\cmd.exe`, it's actually running at:
![image](https://github.com/user-attachments/assets/e812849b-a6a9-409c-b0b9-a889e4c744c1)

**Comment by KohakuBlueleaf** [comment]
This extension is updated to "TIPO" and have official implementation of comfyui node. I will close this issue since it is outdated.
