### ISSUE TITLE
Prompt Format isn't saved in default values

### ISSUE THREAD

**Issue by PurplefinNeptuna** [KohakuBlueleaf/z-tipo-extension#10]
I use Stable UI Forge in Linux.
I use this tools for model other than Kohaku-XL too, but they has different recommended prompt format, when I changed them, it wont be saved for the next time i use stable ui again.

**Comment by KohakuBlueleaf** [comment]
![image](https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg/assets/59680068/3483b2cf-41dc-4607-b473-e3d2d76ad78f)
Stable Diffusion Webui allow you to save default value.
Use that utils.

**Comment by PurplefinNeptuna** [comment]
i know that, but prompt format isn't saved using that, ui-config.json has no entry for prompt format after saving defaults

here's my ui-config:
[ui-config.json](https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg/files/15142808/ui-config.json)
as you can see from that file from line 1722 to 1784, no entry for prompt format there. so the prompt format still will reset after restart.

**Comment by KohakuBlueleaf** [comment]
it looks like TextArea will be ignored in default value system.
Will try to figure it out

**Comment by KohakuBlueleaf** [comment]
Current default value system looks like support TextArea.
I will close this issue
