### ISSUE TITLE
Feature Request: Add a ByPass trigger for fast forward

### ISSUE THREAD

**Issue by mirabarukaso** [KohakuBlueleaf/z-tipo-extension#23]
Hi there,

Really impressed with the fine tuning of your model. For some reason, I often need to enable/disable your node. Please consider adding a "ByPass" trigger in your node so that I can easily connect another bool trigger to control it.

Thanks

For example:
In def INPUT_TYPES(cls):
`
"bypass": ("BOOLEAN", {"default": False}),
`

In def execute(      
`  
        if bypass is True:   
            return(tags, '', '', '',)   
`

**Comment by KohakuBlueleaf** [comment]
Ummm
I think this should be some standalone utilities node which can switch the flow

Instead of adding this option to all the nodes that need this

**Comment by mirabarukaso** [comment]
I thought it would be great for regional condition. But after some tests, the result is not good. For non-regional use, the fast bypass is sufficient. I'll close this issue, sorry for the confusion.
