### ISSUE TITLE
Comfyui error   parse_tipo_request() got an unexpected keyword argument 'nl_length_target'

### ISSUE THREAD

**Issue by nicedoctors** [KohakuBlueleaf/z-tipo-extension#26]
pls help
[TIPO-KGen]-|18:45:00|-INFO: Llama-cpp-python/gguf model TIPO-500M_TIPO-500M_epoch5-F16.gguf loaded
[TIPO-KGen]-|18:45:00|-WARNING: llama.cpp have reproducibility issue on cuda (https://github.com/ggerganov/llama.cpp/pull/1346) It is suggested to use cpu or compile llama-cpp-python by yourself and set GGML_CUDA_MAX_STREAMS in the file ggml-cuda.cu to 1.
!!! Exception during processing !!! parse_tipo_request() got an unexpected keyword argument 'nl_length_target'
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.3\custom_nodes\z-tipo-extension\nodes\tipo.py", line 315, in execute
    meta, operations, general, nl_prompt = parse_tipo_request(
TypeError: parse_tipo_request() got an unexpected keyword argument 'nl_length_target'

Prompt executed in 0.08 seconds
got prompt
!!! Exception during processing !!! parse_tipo_request() got an unexpected keyword argument 'nl_length_target'
![image](https://github.com/user-attachments/assets/05ab8eba-50ac-495a-a0e0-a4cd75778faa)

Thanks.

**Comment by KohakuBlueleaf** [comment]
update the `tipo-kgen` library to >=0.1.2
I'm implementing better automatic installation system for my extension
