### ISSUE TITLE
Can I hide the Natural Language Prompt and TIPO?

### ISSUE THREAD

**Issue by rurika1990** [KohakuBlueleaf/z-tipo-extension#28]
After the update, boxes for Natural Language Prompt and TIPO have been added between the prompt and the negative prompt. However, since I don't use them, the screen feels crowded and hard to read. Is there a setting to hide these?

**Comment by KohakuBlueleaf** [comment]
I will try to implement some layout selection.

**Comment by KohakuBlueleaf** [comment]
implemented.
