### ISSUE TITLE
(feature request) add an "ignored tags" section

### ISSUE THREAD

**Issue by Hugs288** [KohakuBlueleaf/z-tipo-extension#35]
a selection of tags that simply wont be fed to the LLM, this would be useful because for example, one of my loras uses "m40z1d4n" trigger word, and because it contains "m4" it makes it generate all sorts of military tags

**Comment by KohakuBlueleaf** [comment]
you can put your special trigger word in "format", than the TIPO will not process it (if you are using A1111, change the output format to custom)
