### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by Krek12** [KohakuBlueleaf/z-tipo-extension#36]
![Снимок экрана 2024-10-29 203251](https://github.com/user-attachments/assets/ec01e528-8d4b-4a35-8e33-ae794f1093cb)
![Снимок экрана 2024-10-29 203238](https://github.com/user-attachments/assets/341bcff3-20c3-4edc-b014-878ab54ad2d5)

**Comment by Krek12** [comment]
> попробуйте зайти в каталог расширений, models, удалить модель и попробовать загрузить заново, это может исправить проблему

![image](https://github.com/user-attachments/assets/5e79f970-f12f-4ae8-a627-99efd12e43e7)
![image](https://github.com/user-attachments/assets/6acecc64-90d9-4a3a-b5fe-af15b19234a2)
![image](https://github.com/user-attachments/assets/b83fcdd6-7c8b-4968-a930-82f5ee149858)

**Comment by KohakuBlueleaf** [comment]
it looks like your environment is broken.
please try to delete your venv and recreate it
also please check your sd webui is at latest dev
