### ISSUE TITLE
Node not showing up in ComfyUI after install

### ISSUE THREAD

**Issue by danganbenpa** [KohakuBlueleaf/z-tipo-extension#37]
Hi.

The node won't show up in ComfyUI after I git cloned it into my custom nodes folder. I tried installing requirements from the requirements txt file but it didn't help.

**Comment by KohakuBlueleaf** [comment]
If there are no any error it may means you should try to update your ComfyUI
if there are any error please provide

**Comment by KohakuBlueleaf** [comment]
I will close this issue until more info provided
