### ISSUE TITLE
TIPO  interpreting parentheses as emphasis?

### ISSUE THREAD

**Issue by MondayMonkey1** [KohakuBlueleaf/z-tipo-extension#39]
When a word like "charactername (series)" is included in positive prompt, TIPO seems to interpret parentheses as emphasis resulting TIPO output prompts become " charactername, (series:1.1)".

Is this supposed to happen? This happens when "Prompt Format" is set to "Tag only" mode. (But not on custom "Prompt Format")

Thanks.

**Comment by KohakuBlueleaf** [comment]
in comfy and sd webui and forge
all the parentheses without black slash are "emphasis"
TIPO will go through sdwebui/comfy's emphasis parsing function than process the result
So this is expected and it just means all your previous prompt (without TIPO) may be wrong.
