### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by shijie12121** [KohakuBlueleaf/z-tipo-extension#40]
部署完毕后，尝试使用实例，出现以下报错
请问这个该如何解决？
Prompt outputs failed validation
TIPO:
- Value not in list: nl_length: '387225337404799' not in ['very_short', 'short', 'long', 'very_long']

<img width="1226" alt="59e2ac450c23ded4b66ced5b6f39085" src="https://github.com/user-attachments/assets/e5a0b23d-cc84-4e98-8634-1f419a531544">

**Comment by KohakuBlueleaf** [comment]
You just updated your extension/custom node to new version which have new argument
please check your input is correct. (for example, manually select long for nl_length)
