### ISSUE TITLE
How to edit prompt box placement?

### ISSUE THREAD

**Issue by Hujikuio** [KohakuBlueleaf/z-tipo-extension#45]
The extra prompt boxes (understandably) get a little funky with the non-default UI, I was just wondering how to edit where the extension places the TIPO boxes and/or moves existing prompt boxes? This is what it looks like in Lobe Theme:

![image](https://github.com/user-attachments/assets/83cbce2f-1eeb-4aa6-b45f-72365de80597)

**Comment by KohakuBlueleaf** [comment]
actually what you get is some how expected ummmm. 
If you don't need extra box you can turn them off in settings.

This is depends on how these theme extension design their css, which will be hard for me to actually adjust it.

**Comment by Hujikuio** [comment]
ah okay, i thought disabling the tipo boxes disabled the processing. thanks!
