### ISSUE TITLE
Its good, but why it checks its requirements every time I start ComfyUI?

### ISSUE THREAD

**Issue by Mescalamba** [KohakuBlueleaf/z-tipo-extension#48]
It does very verbose check of requirements every time I start ComfyUI. A tiny bit irritating.

Btw. having those tags in form of LORA for lets say Llama 3.2 3B would be pretty good.. Or higher, L3 8B maybe.

**Comment by KohakuBlueleaf** [comment]
Will check the requirements problem 

Also, I think you just don't really know what you are saying.

You can achieve memorizing effect easily on 400~500M model and you want a 3B or 8B base.

I will recommend you to do it by yourself, you are not my boss and you pay nothing for this.

**Comment by KohakuBlueleaf** [comment]
Just FYI
The 500M one requires me to spend 2000~USD to train for only 5 epoch on my current dataset.
I can ensure L3 3/8B with PEFT will cost MORE for it.
And it just meaningless, it will not be better, the L3 pretraining is not helpful for the task, it is also very slow and requires tons of vram.

It is TOTALLY MEANINGLESS to train prompt gen on B level model.

**Comment by KohakuBlueleaf** [comment]
@Mescalamba 
requirement problem is resolved
update the extension and tipo-kgen to 0.1.6 can solve the problem.
