### ISSUE TITLE
"Prompt" output is missing some tags compared to "Unformatted prompt"

### ISSUE THREAD

**Issue by twe00074** [KohakuBlueleaf/z-tipo-extension#49]
![image](https://github.com/user-attachments/assets/893090e5-3346-454c-b1ad-81ad9a40752c)

**Comment by KohakuBlueleaf** [comment]
You forgot to add backslash for brackets 
It will be treated as emphasis instead of part of tag.

**Comment by twe00074** [comment]
But this prompt is from your demo on huggingface

**Comment by KohakuBlueleaf** [comment]
> But this prompt is from your demo on huggingface. Thanks for reminder about backslashes

Because it is huggingface space with diffusers, not comfy ui.
