### ISSUE TITLE
TIPO node output is nondeterministic on CPU and GPU

### ISSUE THREAD

**Issue by asagi4** [KohakuBlueleaf/z-tipo-extension#51]
On my system, the output of the TIPO node with GGUF models is always non-deterministic, regardless of if CPU of GPU is used. Setting a seed does not seem to keep the output stable at all.

I have version 0.3.2 of the llama-cpp-python package, with python 3.11, that I compiled myself. In this version GGML_CUDA_MAX_STREAMS should no longer be a source of nondeterminism, but I compiled with it set to 1 nonetheless. It seems to make no difference.

I thought about testing with 0.2.90 too, but I haven't compiled it yet.

The transformers models are stable with a seed, but they are quite slow to run even on GPU (almost as slow as GGUF on CPU). :/

When loading the models, I get this message:
```
llama_new_context_with_model: n_ctx_per_seq (1024) < n_ctx_train (2048) -- the full capacity of the model will not be utilized
```
I don't know if it's relevant.

**Comment by asagi4** [comment]
Tested with 0.2.90 too with the streams override; same problem there, CPU and GPU are both unstable.

**Comment by KohakuBlueleaf** [comment]
This issue should be posted to llama.cpp
Not here.

**Comment by KohakuBlueleaf** [comment]
I try to reproduce this problem in my computer and only CUDA have nondeterministic issue which is expected for me.
I will say this is llama.cpp or llama-cpp-python issue currently and close this issue.

If you have more observation or experiment result. please let me know and feel free to reopen this issue.
