### ISSUE TITLE
When I run the demo workflow I get an error

### ISSUE THREAD

**Issue by buhibuhiunti** [KohakuBlueleaf/z-tipo-extension#52]
When I run the TIPO node, the following error is displayed:

Prompt outputs failed validation
TIPO:

- Value not in list: nl_length: '387225337404799' not in ['very_short', 'short', 'long', 'very_long']

Failed to validate prompt for output 45:

* TIPO 38:

- Value not in list: nl_length: '387225337404799' not in ['very_short', 'short', 'long', 'very_long']

Output will be ignored
Failed to validate prompt for output 48:
Output will be ignored
Failed to validate prompt for output 46:
Output will be ignored
Failed to validate prompt for output 49:
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

**Comment by KohakuBlueleaf** [comment]
Some updates of the node introduce new option while loading the demo workflow will cause problem
please try to click each option manually and select some(or input some) reasonable value.
I will update demo workflow soon!

**Comment by buhibuhiunti** [comment]
I tried changing some values ​​but it didn't work. What values ​​should I use to make it work?

**Comment by tushar-chaudhary** [comment]
> I tried changing some values ​​but it didn't work. What values ​​should I use to make it work?

Can you share your workflow file, if you are have any workaround
