### ISSUE TITLE
Using the same seed and prompt word cannot completely reproduce the image after restarting the webui.

### ISSUE THREAD

**Issue by hiiii65** [KohakuBlueleaf/z-tipo-extension#54]
Using the same seed and prompt word cannot completely reproduce the image after restarting the webui.

**Comment by KohakuBlueleaf** [comment]
expected.
you can try to update the extension (which should automatically load newest KGen which solve SOME reproducibility issue)
Also, some version of llama-cpp-python with cuda mode DO NOT ensure any reproducibility.

The metadata in image should provide the generated prompt, and the extension provide "apply original propmt"(or apply generated prompt?, I forgot) button to load the generated prompt.

**Comment by KohakuBlueleaf** [comment]
If you want to know why restarting webui cause it
it is bcuz my function will cache the result and if all the things are same it will return same result without calling prompt gen to reduce time cost.
