### ISSUE TITLE
[Feature Request] please add text input node connection option to comfyui node

### ISSUE THREAD

**Issue by Hugs288** [KohakuBlueleaf/z-tipo-extension#57]
i am pretty sure it is impossible to use wildcards with tipo in comfyui because of this

**Comment by KohakuBlueleaf** [comment]
?
In comfy UI you can convert ANY node input become connection input.
![image](https://github.com/user-attachments/assets/85531e49-52e3-466c-a18e-b5565bb78923)

**Comment by Hugs288** [comment]
oh, i didnt know that, sorry.
