### ISSUE TITLE
tipo 疑问

### ISSUE THREAD

**Issue by Chengym2023** [KohakuBlueleaf/z-tipo-extension#58]
![image](https://github.com/user-attachments/assets/4872c118-e62a-41e6-bcdf-0c7e2aa20723)
1.这个宽高设置的作用是什么?
2.ban tags 是什么?

**Comment by Chengym2023** [comment]
试用了一下发现以下问题:
1.比如输入1girl, spark \(pokemon go\), pokemon, 在prompt输出:1girl, pokemon,貌似\(\)这样的格式的都会被吞.
2.
![image](https://github.com/user-attachments/assets/a41e6b8d-2cc0-495a-a42e-f0fc4f3f1717)
这个有什么用?我看输出的prompt也没有artist和quality之类?

**Comment by KohakuBlueleaf** [comment]
1. The content of image is actually related to the aspect ratio, width and height will be used for calculating the aspect ratio as input of TIPO
2. In some cases you don't want the result prompt to have certain key words or tags, use ban tags and the system will automatically remove the matched tag/sentences. It support regex by the way.
3. artist and quality will be adapted from your input directly, the model normally will not generate them. In theory you can let the model to generate "artist tag" but it require some modifications.
