### ISSUE TITLE
background and model

### ISSUE THREAD

**Issue by Chengym2023** [KohakuBlueleaf/z-tipo-extension#59]
i am using model TIPO-500M_TIPO-500M_epoch5-F16.
about background ,it seem always write background like simple background ,white background..etc,how to Generate a slightly more complex background?
about model,which model suggent use?

**Comment by KohakuBlueleaf** [comment]
You just need to utilise ban tags and background as one of banned tag

Or you can add scenery as one of input tag.

The TIPO model will try to reproduce the distribution of danbooru which have tons of simplr background 
So the best way to avoid them is utilizing built-in ban tag feature

**Comment by KohakuBlueleaf** [comment]
Also, github issue is not for these questions.
You can open discussions instead of issue.

**Comment by Chengym2023** [comment]
i add simple background,white background to ban tags,but it Generate grey background ^-^

**Comment by KohakuBlueleaf** [comment]
> i add simple background,white background to ban tags,but it Generate grey background ^-^

I said, add "background" to ban tags.

**Comment by Chengym2023** [comment]
> > i add simple background,white background to ban tags,but it Generate grey background ^-^
> 
> I said, add "background" to ban tags.

ok
